#This program takes in the length n of a sequence and prints out the first n numbers of that sequence
#The sequence in question works as such that each subsequent number generated by it is the sum of the last three numbers

#User inputs
 
n = int(input("Enter the length of the sequence: "))

#We want to implement some sort of way for the program to keep track of the last three numbers
#that the sequence generated

#We initialize the first three numbers in the sequence as well as a variable that is capable of storing the next number generated
first_num = 1
second_num = 2
third_num = 3

next_num = 0
#We want to loop through the entirety of the sequence length, in this case we use a for loop
for i in range(1,n+1):
    print(first_num)                               #print the first number, which will take on the value of each subsequent value in the sequence
    next_num = first_num + second_num + third_num  #store the next number in the sequence by summing up the last three

    first_num = second_num                         #we want to swap the values of the variables we are using for the next iteration of the loop
    second_num = third_num
    third_num = next_num



